### ISSUE TITLE
Could not use "rpkamp\FancyTestdoxPrinter" as printer.

### ISSUE THREAD

**Issue by fcojavierdomenech** [rpkamp/fancy-testdox-printer#14]
> ➜  tests composer require rpkamp/fancy-testdox-printer --dev
> Using version ^0.2.5 for rpkamp/fancy-testdox-printer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating autoload files
> ➜  tests php -v
> PHP 7.1.11-1+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Oct 27 2017 13:50:57) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.1.11-1+ubuntu17.10.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
>     with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
> ➜  tests phpunit controllers/Mcps_test.php 
> PHPUnit 5.4.6 by Sebastian Bergmann and contributors.
> 
> Could not use "rpkamp\FancyTestdoxPrinter" as printer.
>

**Comment by rpkamp** [comment]
You are running PHPUnit 5, which is not supported by this printer. Only PHPUnit 6 is supported.
