### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by theofidry** [rpkamp/fancy-testdox-printer#3]
I quite like it, this is a great improvement over the default testdox printer. But to be really honest, I would find it ever better if it was the same as for phpspec, which I find have been well polished over time.

**Comment by rpkamp** [comment]
I'm not familiar with the phpspec output. What do you like about it specifically?

**Comment by theofidry** [comment]
Basically the idea is the same, the difference is that they had 4
successful major versions to polish it. It's mostly in the details, on top
of my head the spacing in the default output is more pleasant, I like the
colors they put for skipped or failing tests, the diff and colors for the
diffs on a failure.

**Comment by rpkamp** [comment]
I'm not going to completely rebuild what someone else has already built.

If you have something concrete feel free to open a new issue, but for now I'm closing this issue.

**Comment by theofidry** [comment]
>I'm not going to completely rebuild what someone else has already built.

It would be fine if what existed could be re-used, basically my need is mostly having the same output as phpspec for phpunit.

But it's fine if you're not willing to do so, I don't really have the time to do it either :/
