### ISSUE TITLE
PHPUnit version 5.x version?

### ISSUE THREAD

**Issue by bmitch** [rpkamp/fancy-testdox-printer#4]
Currently requires PHP 6.x, any chance of a PHP 5.x version too?

**Comment by rpkamp** [comment]
PHPUnit 5 will not be supported for much longer.

From phpunit.de:

> Support for PHPUnit 5 ends on February 2, 2018.

In general I'm not in favour of actively helping keep legacy alive but I also understand that some are stuck to legacy for reasons beyond their control.

Let me put it this way, if this issue gets 20 :+1: and a reasonable idea on how to properly version this package I'll do it :)

Of course this package has MIT license so everyone is free to fork and change it themselves. I'll be happy to link back.

**Comment by bmitch** [comment]
@rpkamp No problem. Thanks for the cool package.

**Comment by rpkamp** [comment]
I've decided there will be no fancy testdox printer for PHPUnit 5, for reasons described above.
Closing this ticket.
